FROM elasticsearch:7.7.0

# WORKDIR /usr/share/elasticsearch

# RUN mkdir searchqa

# COPY . /searchqa

# RUN yum install -y python3
# RUN yum -y install wget
# RUN yum clean all

# RUN pip3.6 install --upgrade pip

# RUN pip3.6 install --no-cache-dir -r requirements.txt